// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "../public/css/styles.css";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout";
import { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import BottomNav from "@/components/BottomNav";
export const metadata: Metadata = {
  title: "EndPoint Clients | Professional digital solutions",
  description: "EndPoint Clients | Professional digital solutions",
};

const manrope_init = Manrope({
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--manrope",
});

const playfair_init = Playfair_Display({
  style: ["italic"],
  subsets: ["latin"],
  display: "swap",
  
  variable: "--playfair",
});

const setColorSchemeScript = `
(function() {
  try {
    var scheme = localStorage.getItem('color-scheme') || 'light';
    document.documentElement.setAttribute('color-scheme', scheme);
  } catch(e) {}
})();
`;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`no-touch ${manrope_init.variable} ${playfair_init.variable}`}
    >
      <head>
        <link
          rel="icon"
          type="image/png"
          href="favicon/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="favicon/favicon.svg" />
        <link rel="shortcut icon" href="favicon/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="favicon/apple-touch-icon.png"
        />
        <link rel="manifest" href="favicon/site.webmanifest" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script dangerouslySetInnerHTML={{ __html: setColorSchemeScript }} />
      </head>
      <body className={`${manrope_init.variable} ${playfair_init.variable}`}>
        <ClientLayout>{children}</ClientLayout>
        {/* <BottomNav /> */}
      </body>
    </html>
  );
}
